spring :
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test315
    username: postgres
    password: ssafy

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect