spring :
    profiles:
        active: ${profile}
    output:
        ansi:
            enabled: ALWAYS

#logging
logging:
    level:
        root: info
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
    pattern:
        file: "%d %-5level [%thread] %logger : %msg%n"

#swagger
springdoc:
    packages-to-scan: com.dororo.api
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    api-docs:
        path: /api/api-docs
    swagger-ui:
        path: /api/docs # Swagger 페이지로 접속할 경로
        disable-swagger-default-url: true   # 기본 페이지로 리디렉션 되지 않게 하는 설정입니다
        operations-sorter: alpha    # API를 엔드 포인트들의 알파벳 순서로 정렬
        enabled: true   # 외부에서 접속 가능하게 하는 설정