spring :
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://j10e202.p.ssafy.io:5432/dororo_test
        username: postgres
        password: ssafy

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
            format_sql: true
            jdbc:
                lob:
                    non_contextual_creation: true
        database: postgresql
        database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

    profiles:
        active: ${profile}
    output:
        ansi:
            enabled: ALWAYS

#logging
logging:
    level:
        root: info
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
    pattern:
        file: "%d %-5level [%thread] %logger : %msg%n"

#swagger
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true