secret-key: ThisStatementIsJwtSecretKeyDoNotUseThisStatement
spring :
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 4VLJWa1MLPwzhkHz70_h
            client-secret: 0qfLjDeeyr
            redirect-uri: '{baseUrl}/oauth2/callback/naver'
            authorization-grant-type: authorization_code
            scope: name
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dororo_test
    username: postgres
    password: ssafy

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect