spring :
    profiles:
        active: ${profile}
    output:
        ansi:
            enabled: ALWAYS

#logging
logging:
    level:
        root: info
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
    pattern:
        file: "%d %-5level [%thread] %logger : %msg%n"

#swagger
springdoc:
    swagger-ui:
        path: /api/docs # Swagger 페이지로 접속할 경로
        disable-swagger-default-url: true
        operations-sorter: alpha    # API를 엔드 포인트들의 알파벳 순서로 정렬
        enabled: true   # 외부에서 접속 가능하게 하는 설정